blog/urls.py
from django.urls import path
from blog.views import BlogListView, BlogCreateView, BlogDeleteView, BlogUpdateView, BlogDetailView
from blog.apps import BlogConfig
from django.views.decorators.cache import cache_page, never_cache

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogListView.as_view()), name='list'),
    path('create/', never_cache(BlogCreateView.as_view()), name='create'),
    path('delete/<slug:slug>/', never_cache(BlogDeleteView.as_view()), name='delete'),
    path('edit/<slug:slug>/', never_cache(BlogUpdateView.as_view()), name='edit'),
    path('view/<slug:slug>/', cache_page(60)(BlogDetailView.as_view()), name='view'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('message_sendler.urls', namespace='message_sendler')),
                  path('users/', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    body = models.TextField(verbose_name='содержимое')
    articles = models.URLField(max_length=200, verbose_name='статьи', **NULLABLE)
    image = models.ImageField(verbose_name='изображение', **NULLABLE)
    view_count = models.IntegerField(default=0, verbose_name='количество просмотров')
    data = models.DateField(auto_now_add=True, verbose_name='дата публикации')
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'

blog/forms.py
from blog.models import Blog
from django import forms


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class BlogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        exclude = ('view_count', 'slug',)

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView
from blog.models import Blog
from blog.forms import BlogForm
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy, reverse
from django.http import Http404
from pytils.translit import slugify


class BlogListView(ListView):
    model = Blog


class BlogCreateView(PermissionRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm
    permission_required = 'blog.add_blog'
    success_url = reverse_lazy('blog:list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if not self.request.user.has_perm('blog.add_blog'):
            raise Http404
        return self.object

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class BlogDeleteView(PermissionRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')
    permission_required = 'blog.delete_blog'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if not self.request.user.has_perm('blog.delete_blog'):
            raise Http404
        return self.object


class BlogUpdateView(PermissionRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:list')
    permission_required = 'blog.change_blog'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if not self.request.user.has_perm('blog.change_blog'):
            raise Http404
        return self.object

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()
            self.kwargs['slug'] = new_mat.slug

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('slug')])


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        return self.object

blog/templates/blog/blog_confirm_delete.html
{% extends 'message_sendler/base.html' %}
{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить материал "{{ object.header }}" ?</p>
                            <img class="card-img-top"
                                     src="{{ object.image }}"
                                     alt="Card image cap">
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'blog:list' %}" class= "btn btn-warning"> Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'message_sendler/base.html' %}
{% block content %}
    <div class="col-12">
        <div class="row">

            <div class="col-6-text-center">
                <div class="card">
                    <section class="headline">
                        <h1 class="entry-title">
                            {{ object.title }}
                        </h1>
                        <div class="card-body">
                            <img class="card-img-top"
                                 src="{{ object.image }}"
                                 alt="Card image cap">
                        </div>
                    </section>
                    <div class="card-body">
                        <p>
                            {{ object.body }}
                        </p>

                    </div>
                    <div class="card-footer">
                        <p>Просмотры: {{ object.view_count }}</p>
                        <p>Дата публикации: {{ object.data }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'message_sendler/base.html' %}
{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                            <a href="{% url 'blog:list' %}" class= "btn btn-warning"> Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'message_sendler/base.html' %}
{% block content %}
    <div class="container">
        <div class="col-12 mb-5">
            <a class='btn btn-outline-primary' href="{% url 'blog:create' %}">Добавить материал</a>
        </div>
        <div class="row text-center">
            {% for object in object_list %}
                <div class="col-5">
                    <div class="card mb-3 box-shadow">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="my-0 font-weight-normal">{{ object.title }}</h3>
                                <img class="card-img-top"
                                     src="{{ object.image }}"
                                     alt="Card image cap">
                            </div>
                        </div>
                        <div class="card-body">
                            <p>
                                {{ object.body | truncatechars:100 }}
                            </p>
                        </div>
                        <div class="card-footer">
                            {% if object.articles is None %}
                            {% else %}
                                <p>Ссылки: {{ object.articles }}</p>
                            {% endif %}
                            <p>Дата публикации: {{ object.data }}</p>
                            <p>Просмотры: {{ object.view_count }}</p>
                        </div>
                        <div class="card-footer">
                            <div class="btn-group-toggle">
                                <a href="{% url 'blog:view' object.slug %}"
                                   class="btn btn-sm btn-outline-primary">View</a>
                                {% if perms.blog.change_blog %}
                                    <a href="{% url 'blog:edit' object.slug %}" type="button"
                                       class="btn btn-sm btn-outline-primary">Edit</a>
                                    <a href="{% url 'blog:delete' object.slug %}" type="button"
                                       class="btn btn-sm btn-outline-danger">Delete</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}