blog/urls.py
from django.urls import path
from blog.views import BlogListView, BlogCreateView, BlogDeleteView, BlogUpdateView, BlogDetailView
from blog.apps import BlogConfig
from django.views.decorators.cache import cache_page, never_cache

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogListView.as_view()), name='list'),
    path('create/', never_cache(BlogCreateView.as_view()), name='create'),
    path('delete/<slug:slug>/', never_cache(BlogDeleteView.as_view()), name='delete'),
    path('edit/<slug:slug>/', never_cache(BlogUpdateView.as_view()), name='edit'),
    path('view/<slug:slug>/', cache_page(60)(BlogDetailView.as_view()), name='view'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('message_sendler.urls', namespace='message_sendler')),
                  path('users/', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from django.contrib.auth.views import LoginView, LogoutView
from users.views import RegisterView, ProfileView, generate_new_password, activate_new_user, UsersListView, \
    toggle_activity
from django.views.decorators.cache import cache_page, never_cache

app_name = UsersConfig.name
template_name = 'users/login.html'

urlpatterns = [
    path('', never_cache(LoginView.as_view(template_name=template_name)), name='login'),
    path('logout/', never_cache(LogoutView.as_view()), name='logout'),
    path('register/', never_cache(RegisterView.as_view()), name='register'),
    path('profile/', never_cache(ProfileView.as_view()), name='profile'),
    path('profile/genpassword/', never_cache(generate_new_password), name='generate_new_password'),
    path('activate/<int:pk>/', never_cache(activate_new_user), name='activate'),
    path('list/', cache_page(60)(UsersListView.as_view()), name="list"),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from message_sendler.models import NULLABLE


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='email')

    phone = models.CharField(max_length=30, verbose_name='телефон', **NULLABLE)
    telegram = models.CharField(max_length=50, verbose_name='телеграм', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from users.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms


class FormStileMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserRegisterForm(FormStileMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)


class UserProfileForm(FormStileMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'phone', 'telegram', 'avatar',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()
        

users/views.py
import random

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import redirect, render, get_object_or_404
from django.conf import settings
from django.contrib.auth import get_user_model
from users.models import User
from django.views.generic import CreateView, UpdateView, ListView
from django.urls import reverse_lazy, reverse
from users.forms import UserRegisterForm, UserProfileForm
from users.services import verification


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        verification(user)
        return super().form_valid(form)


def activate_new_user(request, pk):
    user = get_user_model()
    user_for_activate = user.objects.get(id=pk)
    user_for_activate.is_active = True
    user_for_activate.save()
    return render(request, 'users/email_verification.html')


class ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


def generate_new_password(request):
    new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
    send_mail(
        subject='Вы сменили пароль',
        message=f'Ваш новый пароль - {new_password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )
    request.user.set_password(new_password)
    request.user.save()
    return redirect(reverse('users:login'))


class UsersListView(LoginRequiredMixin, ListView):
    model = User


def toggle_activity(request, pk):
    user = get_object_or_404(User, pk=pk)
    if user.is_active:
        user.is_active = False
    else:
        user.is_active = True

    user.save()

    return redirect(reverse('users:list'))

users/templates/users/email_verification.html
{% extends 'message_sendler/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-titile text-center">
                            Верификация
                        </h3>
                    </div>
                    <div class="card-body text-center">
                        <h3>Вы успешно подтвердили свою почту!</h3>
                    </div>
                    <div class="card-footer text-center">
                        <a href="{% url 'users:login' %}" class="btn btn-primary">Войти</a>
                    </div>
                </div>
            </div>
        </form>
    </div>


{% endblock %}

users/templates/users/login.html
{% extends 'message_sendler/base.html' %}

{% block content %}
    <form method="post" class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3>Авторизируйтесь</h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <div class="card-footer">
                    <div class="btn-group-toggle">
                        <button type="submit" class="btn btn-outline-success">Войти</button>
                        <a href="{% url 'users:register' %}" class="btn btn-outline-primary">Создать аккаут</a>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

users/templates/users/register.html
{% extends 'message_sendler/base.html' %}

{% block content %}
    <form method="post" class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3>Зарегистируйтесь</h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-success">Зарегистрироваться</button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

users/templates/users/user_form.html
{% extends 'message_sendler/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-titile">
                            Профиль
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                    </div>
                    <div class="card-footer">

                        <a href="{% url 'users:generate_new_password' %}" class="btn btn-danger">Сгенерировать
                            пароль</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'message_sendler/base.html' %}
{% block content %}
    <div class="container">
        <div class="row text-center">
            {% for object in object_list %}
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="my-0 font-weight-normal">Данные пользователя</h4>
                            </div>
                            <div class="card-body">
                                <p class="my-0 font-weight-normal">{{ object.email }}</p>
                                <p class="my-0 font-weight-normal">{{ object.phone }}</p>
                                <p class="my-0 font-weight-normal">{{ object.telegram }}</p>
                            </div>
                            <div class="card-footer">
                                <div class="btn-group-toggle">
                                    {% if object.is_active %}
                                        <a class="btn btn-warning" href="{% url 'users:toggle_activity' object.pk %}">Заблокировать</a>
                                    {% else %}
                                        <a class="btn btn-success" href="{% url 'users:toggle_activity' object.pk %}">Активировать</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}