blog/urls.py
from django.urls import path
from blog.views import BlogListView, BlogCreateView, BlogDeleteView, BlogUpdateView, BlogDetailView
from blog.apps import BlogConfig
from django.views.decorators.cache import cache_page, never_cache

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(BlogListView.as_view()), name='list'),
    path('create/', never_cache(BlogCreateView.as_view()), name='create'),
    path('delete/<slug:slug>/', never_cache(BlogDeleteView.as_view()), name='delete'),
    path('edit/<slug:slug>/', never_cache(BlogUpdateView.as_view()), name='edit'),
    path('view/<slug:slug>/', cache_page(60)(BlogDetailView.as_view()), name='view'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('message_sendler.urls', namespace='message_sendler')),
                  path('users/', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

message_sendler/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import cache_page, never_cache

from message_sendler.apps import MessageSendlerConfig
from message_sendler.views import HomeView, ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, \
    MailingSettingsListView, MailingSettingsCreateView, MailingSettingsDeleteView, MailingSettingsUpdateView, \
    MessageListView, MessageCreateView, MessageUpdateView, MessageDeleteView, MailingClintListView, toggle_client, \
    MailingLogListView, ContactsTemplateView

app_name = MessageSendlerConfig.name

urlpatterns = [
    path('', HomeView.as_view(), name='main'),

    path('clients/', cache_page(60)(ClientListView.as_view()), name='client_list'),
    path('clients/create/', never_cache(ClientCreateView.as_view()), name='client_create'),
    path('clients/edit/<int:pk>/', never_cache(ClientUpdateView.as_view()), name='client_edit'),
    path('clients/delete/<int:pk>/', never_cache(ClientDeleteView.as_view()), name='client_delete'),

    path('settings/', cache_page(60)(MailingSettingsListView.as_view()), name='mailing_list'),
    path('settings/create/', never_cache(MailingSettingsCreateView.as_view()), name='mailing_create'),
    path('settings/edit/<int:pk>/', never_cache(MailingSettingsUpdateView.as_view()), name='mailing_edit'),
    path('settings/delete/<int:pk>/', never_cache(MailingSettingsDeleteView.as_view()), name='meiling_delete'),

    path('message/', cache_page(60)(MessageListView.as_view()), name='message_list'),
    path('message/create/', never_cache(MessageCreateView.as_view()), name='message_create'),
    path('message/edit/<int:pk>/', never_cache(MessageUpdateView.as_view()), name='message_edit'),
    path('message/delete/<int:pk>/', never_cache(MessageDeleteView.as_view()), name='message_delete'),

    path('settings/<int:pk>/client_list', cache_page(60)(MailingClintListView.as_view()), name='mailing_client'),
    path('settings/<int:pk>/clients/<int:client_pk>', never_cache(toggle_client), name='mailing_client_toggle'),

    path('mailinglogs/', cache_page(60)(MailingLogListView.as_view()), name='mailing_logs'),
    path('contacts/', cache_page(60)(ContactsTemplateView.as_view()), name='contacts'),
]

message_sendler/models.py
from django.db import models
import datetime
from django.conf import settings

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    name = models.CharField(max_length=200, verbose_name='ФИО')
    email = models.EmailField(verbose_name='почта', unique=True)
    comment = models.TextField(verbose_name='коментарий', **NULLABLE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, **NULLABLE,
                              verbose_name='пользователь')

    def __str__(self):
        return f'{self.name} - {self.email}'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'


class Message(models.Model):
    title_message = models.CharField(max_length=200, verbose_name='тема письма', **NULLABLE)
    body_message = models.TextField(verbose_name='письмо', **NULLABLE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, **NULLABLE,
                              verbose_name='пользователь')

    def __str__(self):
        return f'{self.body_message}'

    class Meta:
        verbose_name = 'Письмо'
        verbose_name_plural = 'Письма'


class MailingSettings(models.Model):
    PERIOD_DAILY = 'daily'
    PERIOD_WEEKLY = 'weekly'
    PERIOD_MONTHLY = 'monthly'

    PERIODS = (
        (PERIOD_DAILY, 'Ежедневная'),
        (PERIOD_WEEKLY, 'Раз в неделю'),
        (PERIOD_MONTHLY, 'Раз в месяц'),
    )

    STATUS_CREATED = 'created'
    STATUS_STARTED = 'started'
    STATUS_DONE = 'done'

    STATUSES = (
        (STATUS_CREATED, 'Создана'),
        (STATUS_STARTED, 'Запущена'),
        (STATUS_DONE, 'Завершена'),
    )
    start_time = models.DateTimeField(verbose_name='время начала', default=datetime.datetime.now(datetime.timezone.utc))
    finish_time = models.DateTimeField(verbose_name='время окончания',
                                       default=datetime.datetime.now(datetime.timezone.utc) + datetime.timedelta(
                                           days=7))
    status = models.CharField(max_length=20, default=STATUS_CREATED, choices=STATUSES, verbose_name='статус рассылки')
    periodicity = models.CharField(max_length=20, default=PERIOD_DAILY, choices=PERIODS, verbose_name='периодичность')

    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='Сообщение', **NULLABLE)

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, **NULLABLE,
                              verbose_name='пользователь')

    def __str__(self):
        return f'{self.start_time}/ {self.periodicity}'

    class Meta:
        verbose_name = 'Настройка рассылки'
        verbose_name_plural = 'Настройки рассылки'


class MailingLog(models.Model):
    STATUS_OK = 'ok'
    STATUS_FAILED = 'failed'

    STATUSES = (
        (STATUS_OK, 'Успешно'),
        (STATUS_FAILED, 'Ошибка'),
    )
    last_attempt = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время посденей попытки')
    status = models.CharField(default=STATUS_OK, choices=STATUSES, verbose_name='статус попытки')
    mailing_service_response = models.TextField(verbose_name='Ответ почтового сервиса', **NULLABLE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='клиент')
    mailing = models.ForeignKey(MailingSettings, on_delete=models.CASCADE, verbose_name='Рассылка')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, **NULLABLE,
                              verbose_name='пользователь')

    def __str__(self):
        return f'{self.last_attempt} - {self.status}'

    class Meta:
        verbose_name = 'лог'
        verbose_name_plural = 'логи'


class MailingClient(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='клиент')
    mailing = models.ForeignKey(MailingSettings, on_delete=models.CASCADE, verbose_name='рассылка')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, **NULLABLE,
                              verbose_name='пользователь')

    def __str__(self):
        return f'{self.client} - {self.mailing}'

    class Meta:
        verbose_name = 'Список рассылки'
        verbose_name_plural = 'Список рассылок'

message_sendler/forms.py
from django import forms
from message_sendler.models import MailingSettings, Client, Message


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingSettingsForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingSettings
        fields = '__all__'


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        fields = '__all__'


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        fields = '__all__'


class MailingSettingsForManagerForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingSettings
        fields = ('status',)

message_sendler/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, TemplateView, UpdateView, DeleteView, CreateView
from blog.models import Blog
from message_sendler.models import MailingSettings, Client, Message, MailingClient, MailingLog
from message_sendler.forms import MessageForm, MailingSettingsForm, ClientForm, MailingSettingsForManagerForm


class ContactsTemplateView(TemplateView):
    template_name = 'message_sendler/contacts.html'
    extra_context = {
        'title': 'Контакты'
    }

    def post(self, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        if self.request.method == "POST":
            name = self.request.POST.get('name')
            email = self.request.POST.get('email')
            message = self.request.POST.get('message')
            print(f'New message from {name}, {email}: {message}')
        return super().get_context_data(**kwargs)


class HomeView(TemplateView):
    template_name = 'message_sendler/home.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['count_mailing'] = MailingSettings.objects.all().count()
        context_data['count_mailing_active'] = MailingSettings.objects.filter(status=3).count()
        context_data['count_unique_customers'] = Client.objects.distinct().count()
        context_data['title'] = 'Главная страница рассылок'
        context_data['blog'] = Blog.objects.all()[:3]
        return context_data


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    template_name = 'message_sendler/client_list.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_staff:
            return queryset
        return queryset.filter(owner=self.request.user)


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    template_name = 'message_sendler/client_form.html'
    success_url = reverse_lazy('message_sendler:client_list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    template_name = 'message_sendler/client_form.html'
    success_url = reverse_lazy('message_sendler:client_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user:
            raise Http404
        return self.object


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    template_name = 'message_sendler/client_confirm_delete.html'
    success_url = reverse_lazy('message_sendler:client_list')

    def get_object(self, queryset=None):
        """ Проверка на то, что пользователь не может удалить чужого клиента """
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user:
            raise Http404
        return self.object


class MailingSettingsListView(LoginRequiredMixin, ListView):
    model = MailingSettings
    template_name = 'message_sendler/mailinglist_list.html'

    def get_queryset(self):
        """Пользователь видит только свои рассылки"""
        queryset = super().get_queryset()
        if self.request.user.is_staff:
            return queryset  # Если есть право доступа, то пользователь видит все рассылки
        return queryset.filter(owner=self.request.user)


class MailingSettingsCreateView(LoginRequiredMixin, CreateView):
    model = MailingSettings
    form_class = MailingSettingsForm
    template_name = 'message_sendler/mailinglist_form.html'
    success_url = reverse_lazy('message_sendler:mailing_list')

    def form_valid(self, form):
        """ У рассылки появляется 'owner' - авторизированный пользователь """
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class MailingSettingsUpdateView(LoginRequiredMixin, UpdateView):
    model = MailingSettings
    template_name = 'message_sendler/mailinglist_form.html'
    success_url = reverse_lazy('message_sendler:mailing_list')

    def get_form_class(self):
        user = self.request.user
        mailing = self.object
        if mailing.owner == user or user.is_superuser:
            self.form_class = MailingSettingsForm
            return self.form_class
        elif mailing.owner == user and user.is_staff:
            self.form_class = MailingSettingsForm
            return self.form_class
        else:
            self.form_class = MailingSettingsForManagerForm
            return self.form_class


class MailingSettingsDeleteView(LoginRequiredMixin, DeleteView):
    model = MailingSettings
    template_name = 'message_sendler/mailinglist_confirm_delete.html'
    success_url = reverse_lazy('message_sendler:mailing_list')
    permission_required = 'message_sendler.change_mailingsettings'

    def get_object(self, queryset=None):
        """ Проверка на то, что пользователь не может удалять чужое сообщение """
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user:
            raise Http404
        return self.object


class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    template_name = 'message_sendler/message_list.html'

    def get_queryset(self):
        """Пользователь видит только свои сообщения"""
        queryset = super().get_queryset()
        if self.request.user.has_perm('mailing.view_mailingmessage'):
            return queryset  # Если есть право доступа, то пользователь видит все сообщения
        return super().get_queryset().filter(owner=self.request.user)


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    template_name = 'message_sendler/message_form.html'
    success_url = reverse_lazy('message_sendler:message_list')

    def form_valid(self, form):
        """ У сообщения появляется 'owner' - авторизированный пользователь """
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    template_name = 'message_sendler/message_form.html'
    success_url = reverse_lazy('message_sendler:message_list')

    def get_object(self, queryset=None):
        """ Проверка на то, что пользователь не может менять чужое сообщение """
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user:
            raise Http404
        return self.object


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    template_name = ''
    success_url = reverse_lazy('message_sendler:message_list')

    def get_object(self, queryset=None):
        """ Проверка на то, что пользователь не может удалять чужое сообщение """
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user:
            raise Http404
        return self.object


class MailingClintListView(PermissionRequiredMixin, ListView):
    model = MailingClient
    template_name = 'message_sendler/mailingclient_list.html'
    permission_required = 'message_sendler.view_mailingclient'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(mailing=self.kwargs.get('pk'))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['clients'] = Client.objects.filter(owner=self.request.user)
        context_data['mailing_pk'] = self.kwargs.get('pk')

        return context_data


def toggle_client(request, pk, client_pk):
    if MailingClient.objects.filter(client_id=client_pk, mailing_id=pk).exists():
        MailingClient.objects.filter(client_id=client_pk, mailing_id=pk).delete()
    else:
        MailingClient.objects.create(client_id=client_pk, mailing_id=pk)
    return redirect(reverse('message_sendler:mailing_client', args=[pk]))


class MailingLogListView(ListView):
    model = MailingLog

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.has_perm('message_sendler.view_mailinglog'):
            return queryset
        return queryset.filter(owner=self.request.user)

message_sendler/templates/message_sendler/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <!-- Bootstrap core CSS -->
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static '/css/form-validation.css' %}" rel="stylesheet">
</head>
{% include 'message_sendler/includes/inc_main_menu.html' %}
<body class="bg-light">

<div class="container">
    <div class="py-5 text-center">
        <h2>Сервис по работе с клиентами</h2>
        <p class="lead"></p>
    </div>
    {% block content %}
    {% endblock %}
    <footer class="my-5 pt-5 text-muted text-center text-small">
    </footer>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static '/js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static '/js/holder.min.js' %}"></script>
<script>
    // Example starter JavaScript for disabling form submissions if there are invalid fields
</script>


</body>
</html>

message_sendler/templates/message_sendler/client_confirm_delete.html
{% extends 'message_sendler/base.html' %}
{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить клиента "{{ object.name }}" ?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'message_sendler:client_list' %}" class="btn btn-warning"> Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

message_sendler/templates/message_sendler/client_detail.html
{% extends 'message_sendler/base.html' %}
{% block content %}
    <div class="col-12">
        <div class="row">

            <div class="col-6-text-center">
                <div class="card">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                    </div>
                    <div class="card-body">
                        <p>
                            {{ object.email }}
                        </p>
                    </div>
                    <div class="card-header">
                        <p>
                            {{ object.comment }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

message_sendler/templates/message_sendler/client_form.html
{% extends 'message_sendler/base.html' %}
{% block content %}
       <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Добавить
                                {% endif %}
                            </button>
                            <a href="{% url 'message_sendler:client_list' %}" class= "btn btn-warning"> Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

message_sendler/templates/message_sendler/client_list.html
{% extends 'message_sendler/base.html' %}
{% block content %}
    <div class="container">
        <div class="col-12 mb-5">
            <a class='btn btn-outline-primary' href="{% url 'message_sendler:client_create' %}">Добавить клиента</a>
        </div>
        <div class="row text-center">
            {% for object in object_list %}
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                            </div>
                            <div class="card-body">
                                <p>
                                    {{ object.comment | truncatechars:100 }}
                                </p>
                                {% if user.is_staff %}
                                    <hr>
                                    {{ object.owner }}
                                {% endif %}
                            </div>
                            <div class="card-footer">
                                <div class="d-flex justify-content-between align-items-center">

                                    <div class="btn-group-toggle">
                                        <a href="{% url 'message_sendler:client_edit' object.pk %}" type="button"
                                           class="btn btn-sm btn-outline-success">Edit</a>
                                        <a href="{% url 'message_sendler:client_delete' object.pk %}" type="button"
                                           class="btn btn-sm btn-outline-danger">Delete</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

message_sendler/templates/message_sendler/home.html
{% extends 'message_sendler/base.html' %}
{% block content %}

    <div class="col-12">
        <div class="card mb-5 bg-transparent" style="margin-top: 50px">
            <div class="card-header">
                <h1>Cервис рассылок</h1>
            </div>
            <div class="card-body">
                <p>Всего рассылок : {{ count_mailing }}</p>
                <p>Активных рассылок всего : {{ count_mailing_active }}</p>
                <p>Количество уникальных клиентов для рассылок : {{ count_unique_customers }}</p>
            </div>
        </div>
    </div>
    <div class="row mt-3">
        {% for object in blog %}
            <div class="col-4">
                <div class="card mb-3 box-shadow">
                    <div class="card-header">
                        <h5> {{ object.title }}</h5>
                        <img src="{{ object.image}}" class="card-img-top" alt="...">
                    </div>
                    <div class="card-body">
                        <p>{{ object.body|truncatechars:100 }}</p>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'blog:view' object.slug %}" class="btn btn-outline-primary border-1">Перейти</a>
                    </div>
                </div>
            </div>
        {% endfor %}
        <div>
{% endblock %}

message_sendler/templates/message_sendler/mailingclient_list.html
{% extends "message_sendler/base.html" %}
{% block content %}

    <div class="row">
        <div class="col-6">
            <div class="col-12 mb-5">
                <p align="center"> Клиенты рассылки</p>
            </div>
            {% for object in object_list %}
                <div class="card bg-transparent">
                    <div class="card-header">
                        {{ object.client.name }}
                    </div>
                    <div class="card-body">
                        {{ object.client.email }}
                    </div>
                    <div class="card-footer">
                        {% if object.client.owner == user %}
                            <a href="{% url 'message_sendler:mailing_client_toggle' mailing_pk object.client.pk %}"
                               class="btn btn-outline-dark">Удалить</a>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>


        <div class="col-6">
            <div class="col-12 mb-5">
                <p align="center"> Клиенты для добавления </p>
            </div>
            <table class="table">
                <tr>
                    <th>Клиент</th>
                    <th>Email</th>
                    <th>Добавить</th>
                </tr>
                {% for client in clients %}
                    <tr>
                        <td>{{ client.name }}</td>
                        <td>{{ client.email }}</td>
                        {% if client.owner == user %}
                            <td><a href="{% url 'message_sendler:mailing_client_toggle' mailing_pk client.pk %}"
                                   class="btn btn-outline-primary">Добавить</a></td>
                        {% endif %}

                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>

{% endblock %}

message_sendler/templates/message_sendler/mailinglist_list.html
{% extends 'message_sendler/base.html' %}
{% block content %}
    <div class="container">
        <div class="col-12 mb-5">
            <a class='btn btn-outline-primary' href="{% url 'message_sendler:mailing_create' %}">Добавить рассылку</a>
        </div>
        <div class="row text-center">
            {% for object in object_list %}
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <p class="my-0 font-weight-normal">Дата начала рассылки: ({{ object.start_time }})</p>
                            <hr>
                            <p class="my-0 font-weight-normal">Дата окончания рассылки: ({{ object.finish_time }})</p>
                        </div>
                        <div class="card-body">
                            <p>
                                Статус рассылки: {{ object.get_status_display }}
                            </p>
                            <p>
                                Периодичность: {{ object.get_periodicity_display }}
                            </p>
                            <p>
                                {% if perms.mailing_list.view_mailingclient %}
                                    <a href="{% url 'message_sendler:mailing_client' object.pk %}">Подписчиков: {{ object.mailingclient_set.count }}</a>
                                {% else %}
                                    Подписчиков: {{ object.mailingclient_set.count }}
                                {% endif %}
                            </p>
                            <p>
                                {% if user.is_staff %}
                                    <hr>
                                    {{ object.owner }}
                                {% endif %}
                            </p>
                        </div>
                        <div class="card-footer">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group-toggle">
                                    <a href="{% url 'message_sendler:mailing_edit' object.pk %}" type="button"
                                       class="btn btn-sm btn-outline-primary">Edit</a>
                                    <a href="{% url 'message_sendler:meiling_delete' object.pk %}" type="button"
                                       class="btn btn-sm btn-outline-danger">Delete</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

message_sendler/templates/message_sendler/message_list.html
{% extends 'message_sendler/base.html' %}
{% block content %}
    <div class="container">
        <div class="col-12 mb-5">
            {% if perms.message_sendler.add_mailinglist %}
                <a class='btn btn-outline-primary' href="{% url 'message_sendler:message_create' %}">Добавить сообщение</a>
            {% endif %}
        </div>
        <div class="row text-center">
            {% for object in object_list %}
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <p>Тема рассылки: {{ object.title_message }}</p>
                        </div>
                        <div class="card-body">
                            <p>Собщение: {{ object.body_message }} </p>
                        </div>
                        <div class="card-footer">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group-toggle">
                                    {% if user.is_superuser %}
                                        <a href="{% url 'message_sendler:message_edit' object.pk %}" type="button"
                                           class="btn btn-sm btn-outline-primary">Edit</a>
                                        <a href="{% url 'message_sendler:message_delete' object.pk %}" type="button"
                                           class="btn btn-sm btn-outline-danger">Delete</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}